spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    host: jdbc:mysql://localhost:3306
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/twms
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
client-authorization:v
  id: tsystems
  secret: tsPassword